[package]
name        = "gn-cli"
description = "git-notes CLI — add, list, show, sync, resolve notes"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "git-notes"
path = "src/main.rs"

[[bin]]
name = "gn"
path = "src/bin/gn.rs"

[dependencies]
gn-core     = { version = "0.1.6", path = "../gn-core" }
gn-sync     = { version = "0.1.6", path = "../gn-sync" }
clap        = { workspace = true, features = ["derive"] }
clap_complete = { workspace = true }
chrono      = { workspace = true }
tracing     = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow      = { workspace = true }
serde       = { workspace = true, features = ["derive"] }
serde_json  = { workspace = true }
uuid        = { workspace = true }
crossterm   = { workspace = true }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
